//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities : DbContext
    {
        public Database1Entities()
            : base("name=Database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Schedule_ch> Schedule_ch { get; set; }
        public virtual DbSet<Schedule_pn> Schedule_pn { get; set; }
        public virtual DbSet<Schedule_pt> Schedule_pt { get; set; }
        public virtual DbSet<Schedule_sb> Schedule_sb { get; set; }
        public virtual DbSet<Schedule_sr> Schedule_sr { get; set; }
        public virtual DbSet<Schedule_vs> Schedule_vs { get; set; }
        public virtual DbSet<Schedule_vt> Schedule_vt { get; set; }
    }
}
